CREATE TABLE IF NOT EXISTS MOVIE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    GENRE VARCHAR(255),
    RELEASE_YEAR INT,
    RATING DECIMAL(3,1)
);

ALTER TABLE MOVIE ADD COLUMN IF NOT EXISTS poster VARCHAR(255);
